default_config = {
    "run_id": "catmap",
    "name": "convlstm_nbody_res",
    "data_path": "/home/ubuntu/imgphys/data/raw.npy",
    "model_path": "/home/ubuntu/imgphys/lightning_logs/catmap_02gdwzrj/epoch=5-step=1500.ckpt",
    "save_path": "/home/ubuntu/imgphys/figures/poster_visuals_res_nbody",
    "reservoir_path": "/home/ubuntu/imgphys/precompute/",
    "accumulate_grad_batches": 1,
    "architecture": "convlstm",
    "convlstm_backbone_kwargs": {
        "architecture": "convlstm",
        "num_layers": 3,  #
        "n_kernels": 5,
        "kernel_size": 3,
        "padding": "same",
        "activation": "relu",
        "reservoir_layers": [1],
    },
    "recurrent_backbone_kwargs": {
        "architecture": "recurrent",
        "num_layers": 3,
        "activation": "tanh",
        # "hidden_size": 512, # 128
        "reservoir_layers": [1],
    },
    "ffn_backbone_kwargs": {
        "architecture": "ffn",
        "activation": "relu",
        "num_layers": 3,
        "reservoir_layers": [],
    },
    "batch_size_train": 32,
    "batch_size_val": 32,
    "check_val_every_n_epoch": 1,  # 50,
    "dataset_dir": "data",
    "gradient_clip_val": None,
    "num_workers": 8,
    "precision": 32,
    "prefetch_factor": 2,
    "dataset_kwargs": {
        "channels": 1,
        "frame_size": (128, 128),
        "transforms": [],  # ["gaussian_noise"],
        "eps": 0,
        "num_frames_prediction": 9,  # How many frames it is given to make next pred
    },
    "seed": 0,
    "lr": 1e-3,
    "learning_rate_scheduler": None,
    "weight_decay": 0.01,
    "n_epochs": 50,
    "shuffle_train": True,
    "reservoir_kwargs": {
        "dim": 64,
        "sparsity": 0.95,
        "spectral_radius": 0.25,
        "leak_rate": 0.1,
        "bias": False,
        "random_projection": "structured",
        "sparse_reservoir": True,
        "nonlinearity": "tanh",
        "skip_transform_enabled": False,
        "skip_dropout_prob": 0,
        "n_reservoirs": 3,
        "collate_method": "sum",
    },
    "train_val_split": 0.8,
    "num_generations": 7,
    "num_samples": 10,
}
