default_config = {
    "data_path": "/home/ubuntu/imgphys/data/raw.npy",
    "model_path": "/home/ubuntu/imgphys/lightning_logs/nq7lc6op/epoch=98-step=198.ckpt",
    "save_path": "/home/ubuntu/imgphys/figures/generations",
    "accumulate_grad_batches": 1,
    "backbone_kwargs": {
        "architecture": "convlstm",
        "num_layers": 3,#
        "n_kernels": 5,
        "kernel_size": 3,
        "padding": "same",
        "activation": "relu",
        "reservoir_layers": [1],
    },
    "batch_size_train": 32,
    "batch_size_val": 32,
    "check_val_every_n_epoch": 1,  # 50,
    "dataset_dir": "data",
    "gradient_clip_val": None,
    "num_workers": 8,
    "precision": 32,

    "prefetch_factor": 2,
    "dataset_kwargs": {
         "channels": 1,  
         "frame_size": (32, 32),
    },
    "seed": 0,
    "lr": 1e-3,
    "learning_rate_scheduler": None,
    "weight_decay": 0.0,
    "n_epochs": 100,
    "shuffle_train": True,
    "reservoir_kwargs": {
        "dim": 64,
        "sparsity": 0.95,
        "spectral_radius": 0.95,
        "max_iter": 3,
        "leak_rate": 0.5,
        "bias": False,
        "random_projection": "structured",
        "sparse_reservoir": True,
        "nonlinearity": "tanh",
        "skip_transform_enabled": False,
        "skip_dropout_prob": 0.0,
    },
    "train_val_split": 0.8,
     "num_generations":10,
}
